### ISSUE TITLE
cannot retrieve result collection from local fractal instance

### ISSUE THREAD

**Issue by pavankum** [openforcefield/openff-qcsubmit#168]
I get this error when I try to retrieve a dataset from a local fractal client, it works fine with QCA. I'm using version 0.2.3.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/homezvol1/pbehara/.conda/envs/qcf-local/lib/python3.9/site-packages/openff/qcsubmit/results/results.py", line 370, in from_server
    return cls.from_datasets(
  File "/data/homezvol1/pbehara/.conda/envs/qcf-local/lib/python3.9/site-packages/openff/qcsubmit/results/results.py", line 283, in from_datasets
    raise TypeError(
TypeError: A ``BasicResultCollection`` can only be created from ``Dataset`` objects.
```

**Comment by pavankum** [comment]
Output of 
```
>> client.get_collection('Dataset', 'OpenFF Theory Benchmarking Single Point Energies v1.0')
<Dataset(name=`OpenFF Theory Benchmarking Single Point Energies v1.0`, id='1', client='https://hpc3-22-04:7777/') >

>> type(client.get_collection('Dataset', 'OpenFF Theory Benchmarking Single Point Energies v1.0'))
<class 'qcfractal.interface.collections.dataset.Dataset'>
```

**Comment by jthorton** [comment]
@pavankum I think this is due to the type check we do in qcsubmit [here](https://github.com/openforcefield/openff-qcsubmit/blob/4306f2c86cf7d5c64dbfb5329402422ad48a2021/openff/qcsubmit/results/results.py#L281). The error you see is due to the use of` qcfractal.interface` rather than `qcportal `. Can you try and make the client using qcportal this should fix the issue.

**Comment by pavankum** [comment]
Perfect! Thank you @jthorton, it works :). Closing the issue.
