### ISSUE TITLE
CI failing due to installation errors

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-qcsubmit#211]
https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232

```
Run python setup.py develop --no-deps
  python setup.py develop --no-deps
  shell: /usr/bin/bash -l {0}
  env:
    OE_LICENSE: /home/runner/work/openff-qcsubmit/openff-qcsubmit/oe_license.txt
    MSYS: winsymlinks:nativestrict
    MAMBA_ROOT_PREFIX: /home/runner/micromamba-root
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
running develop
/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "setup.py", line [2](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:2)4, in <module>
    setup(
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python[3](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:3).8/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi[4](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:4)/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 18[5](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:5), in setup
    return run_commands(dist)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 9[6](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:6)9, in run_commands
    self.run_command(cmd)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 98[7](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:7), in run_command
    cmd_obj.ensure_finalized()
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.[8](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:8)/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/command/develop.py", line 52, in finalize_options
    easy_install.finalize_options(self)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 10[9](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:10)6, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/home/runner/micromamba-root/envs/qcsubmit-test-psi4/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'at[20](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:21)RC5-54.g5702a[23](https://github.com/openforcefield/openff-qcsubmit/actions/runs/4129521413/jobs/7135208232#step:5:24)2fe.dirty' (package: ParmEd)

**Comment by mattwthompson** [comment]
Probably related to this mess https://setuptools.pypa.io/en/latest/history.html#breaking-changes

> [#3790](https://github.com/pypa/setuptools/issues/3790): Bump vendored version of [packaging](https://pypi.org/project/packaging) to 23.0 ([pyparsing](https://pypi.org/project/pyparsing) is no longer required and was removed). As a consequence, users will experience a more strict parsing of requirements. Specifications that don’t comply with [PEP 440](https://peps.python.org/pep-0440/) and [PEP 508](https://peps.python.org/pep-0508/) will result in build errors.
